version: '2.1'

services:
  # Application
  app:
    container_name: app_container_v_lecturenfant
    image: tianon/true
    volumes:
      - ./${REPO_FOLDER}:${DOCUMENT_ROOT}:z
      - ./moodledata:${MOODLE_DATA}:z

  # mariadb
  mariadb:
    container_name: mariadb_container_v_lecturenfant
    image: wodby/mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${SQL_ROOT}"
      MYSQL_DATABASE: "${SQL_DB}"
      MYSQL_USER: "${SQL_USER}"
      MYSQL_PASSWORD: "${SQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_dumps:/backup:z
      - ./lectur_dev_dump.sql:/docker-entrypoint-initdb.d/lectur_dev_dump.sql
    ports:
      - "${IP}:${SQL_PORT}:3306"
    depends_on:
      - app

  # Service for PHP-FPM
  php-fpm:
    container_name: php_fpm_container_v_lecturenfant
    image: "moodledev/php:7.4-fpm"
    build:
      context: ./php-fpm
      args:
        - DOCUMENT_ROOT
        - MY_TZ
    environment:
      - XDEBUG_CONFIG=idekey=PHPTEST
      - PHP_IDE_CONFIG=serverName=localhost
      - DOCUMENT_ROOT
      - SQL_DB
      - SQL_USER
      - SQL_PASSWORD
      - MOODLE_DATA
      - WWWROOT
      - WWW_PORT
    volumes_from:
      - app
    volumes:
      - ./log:/var/log/shared:z
    expose:
      - "${PHP_SOCKET}"
    links:
      - mariadb
    depends_on:
      - mariadb

  # Services for Apache2
  apache2:
    container_name: apache2_container_v_lecturenfant
    image: moodledev/apache2:2.4
    build:
      context: ./apache2
      args:
        DOCUMENT_ROOT: ${DOCUMENT_ROOT}
        PHP_SOCKET: php-fpm:${PHP_SOCKET}
        ALIAS_DOMAIN: ${ALIAS_DOMAIN}
    volumes_from:
      - app
    ports:
      - "${IP}:${WWW_PORT}:80"
    links:
      - php-fpm
      - mariadb
    depends_on:
      - php-fpm

  # Cron for Moodle
  cron:
    container_name: cron_container_v_lecturenfant
    image: moodledev/php:7.4-fpm-cron
    build:
      context: ./cron
      args:
        DOCUMENT_ROOT: ${DOCUMENT_ROOT}
    volumes_from:
      - app
    depends_on:
      - apache2

  # Database manager
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "${IP}:8081:80"
    environment:
      PMA_HOST: mariadb
    links:
      - mariadb
    volumes:
      - ./db_dumps:/var/www/html/upload:z
    depends_on:
      - mariadb

volumes:
  db_data:
    driver: "local"
